Change `app.giantswarm.io/branch` label to `application.giantswarm.io/branch`, `application.kubernetes.io/*` to `app.kubernetes.io/*`
giantswarm/template-app pull request #45
Opened 2024-03-08 12:10 UTC by marians

In the context of https://github.com/giantswarm/roadmap/issues/3295

All other app related labels have the `application.giantswarm.io` prefix since https://github.com/giantswarm/template-app/pull/35, but it seems that `app[lication].giantswarm.io/branch` is the outlier. It might have been missed in an alignment effort.

This PR also changes `application.kubernetes.io/*` to `app.kubernetes.io/*`, since the latter is the official one documented in [[https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/]](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) .

2024-03-08 13:26 UTC, marians commented
CircleCI is expected to fail here because of the placeholder in the config.

2024-03-11 18:25 UTC, stone-z approved these changes

2024-03-12 00:08 UTC, stone-z requested changes
Actually, I'm all for alignment, but I'm not sure this change was correct https://github.com/giantswarm/template-app/commit/5fe5d49c34d4f2956ceefa4f323f436e9fdcd7cc

I can't rabbit hole on this now but will happily re-approve if that change doesn't affect your goal with this PR

2024-03-12 12:59 UTC, marians commented
@stone-z I don't fully understand your comment, unfortunately.

2024-03-12 13:04 UTC, stone-z commented
I was a bit tired :sweat_smile: 

I think your change to the `giantswarm.io` label is fine as-is.
But, the previous change to the `kubernetes.io` label was probably incorrect. I think that one [should still be `app.kubernetes.io`](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/).

This PR could re-align the k8s labels while updating the Giant Swam label.

2024-03-12 13:20 UTC, marians commented
Oh wow, I didn't even notice that https://github.com/giantswarm/template-app/commit/5fe5d49c34d4f2956ceefa4f323f436e9fdcd7cc changed some kubernetes.io labels to giantswarm.io

I also think this was a mistake. Will talk to piontec.

2024-03-12 13:33 UTC, marians commented
PR title description, and content updated. Please take another look @piontec @stone-z

2024-03-12 13:34 UTC, piontec approved these changes

2024-03-12 13:36 UTC, stone-z approved these changes

2024-03-12 13:48 UTC, merged